# Generated by Django 5.0.4 on 2024-06-09 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_num', models.IntegerField(blank=True, null=True)),
                ('term_str', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeekDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_num', models.IntegerField(blank=True, null=True)),
                ('day_str', models.CharField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='submitproject',
            name='course_enroll_id',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='coursegroup',
            name='teacher_id',
        ),
        migrations.RemoveField(
            model_name='faze',
            name='project_id',
        ),
        migrations.RemoveField(
            model_name='section',
            name='faze_id',
        ),
        migrations.RemoveField(
            model_name='projectdefinition',
            name='faze_id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='submitproject',
            name='project_defenition_id',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='section_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='course',
            name='date_edited',
        ),
        migrations.RemoveField(
            model_name='course',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='term_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.terms'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='CourseEnroll',
        ),
        migrations.DeleteModel(
            name='CourseGroup',
        ),
        migrations.DeleteModel(
            name='Faze',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectDefinition',
        ),
        migrations.DeleteModel(
            name='SubmitProject',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
