# Generated by Django 5.0.4 on 2024-05-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_coursegroup_courseenroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date_edited',
            field=models.DateTimeField(null=True),
        ),
    ]
