# Generated by Django 5.0.4 on 2024-06-09 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('course', '0002_terms_weekdays_remove_submitproject_course_enroll_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(null=True)),
                ('finish_date', models.DateField(null=True)),
                ('edited_date', models.DateField(null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('main_mentor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.teacher')),
                ('meta_meeting_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_meeting', to='course.weekdays')),
                ('second_mentor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_mentor', to='account.teacher')),
                ('technical_meeting_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.weekdays')),
            ],
        ),
    ]
