# Generated by Django 5.0.4 on 2024-05-19 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_date_edited_project_faze_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdefinition',
            name='project_image',
            field=models.FileField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='projectdefinition',
            name='project_video',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
