# Generated by Django 5.0.4 on 2024-07-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_coursegroup_second_mentor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklytask',
            name='days_to_complete',
            field=models.DateField(null=True),
        ),
    ]
