# Generated by Django 5.0.4 on 2024-07-21 14:26

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_weeklytask_days_to_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmeetings',
            name='hold_on_date',
            field=django_jalali.db.models.jDateField(null=True),
        ),
    ]
