# Generated by Django 5.0.4 on 2024-06-30 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AddField(
            model_name='student',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
