# Generated by Django 5.0.4 on 2024-06-30 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_student_cv_student_uploaded_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='cv',
        ),
        migrations.RemoveField(
            model_name='student',
            name='uploaded_at',
        ),
        migrations.CreateModel(
            name='Cv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cv', models.FileField(blank=True, null=True, upload_to='cv/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
            ],
        ),
    ]
