# Generated by Django 5.0.4 on 2024-07-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_course_taskfiles_faze_section_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='faze',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
